[build]
  publish = "public"  # Netlify가 public 폴더를 정적 파일 루트로 인식하도록 설정

[[redirects]]
  from = "/"
  to = "/first.html"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
